### ISSUE TITLE
Failed to Start the Listener: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MazenElzanaty** [tiagorlampert/CHAOS#10]
START LISTENER
 --------------------------

 [*] Enter LPORT: 192.138.1.1

 [*] Waiting for connection...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4fb960]

goroutine 1 [running]:
main.RunServer()
	/root/CHAOS/CHAOS.go:505 +0x6d0
main.ShowMenu()
	/root/CHAOS/CHAOS.go:167 +0x96b
main.main()
	/root/CHAOS/CHAOS.go:41 +0x2a
exit status 2

**Comment by tiagorlampert** [comment]
Hi, you entered your IP on LPORT. Enter the local PORT.

Sample:
`
START LISTENER
 --------------------------

 [*] Enter LPORT: 8080

 [*] Waiting for connection...
`

Video demonstration:
https://www.youtube.com/watch?v=QRNN2KwCYOg

**Comment by MazenElzanaty** [comment]
I can't believe i did this lol
