### ISSUE TITLE
Trouble working with heroku?

### ISSUE THREAD

**Issue by cyb3rspace** [tiagorlampert/CHAOS#100]
I can't seem to find which port and ip to use so that my client will connect to my heroku server?

**Comment by tiagorlampert** [comment]
Hi @cyb3rspace 

When deploying on heroku you don't need specify your port since it optional.

You should only type the url host of your app.

Something like that:

![image](https://user-images.githubusercontent.com/29933243/194208320-74492c98-268d-46db-9a7b-4392610b3a62.png)

Any question ping me.

**Comment by Mrpolack** [comment]
same here!
