### ISSUE TITLE
on ubuntu 20.04.5 lts - error missing go 1.16

### ISSUE THREAD

**Issue by Mrpolack** [tiagorlampert/CHAOS#112]
Follow your instruction on"Local Development" i get this error. Any idea how to fix?

# gorm.io/gorm/logger
../go/pkg/mod/gorm.io/gorm@v1.23.10/logger/logger.go:72:24: undefined: io.Discard
note: module requires Go 1.16
# github.com/golang-jwt/jwt/v4
../go/pkg/mod/github.com/golang-jwt/jwt/v4@v4.1.0/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
../go/pkg/mod/github.com/golang-jwt/jwt/v4@v4.1.0/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)
note: module requires Go 1.15

**Comment by tiagorlampert** [comment]
Looks like you are running a old golang version.

Make sure to run go 1.18 or greater.

To check your version run on terminal:

```bash
go version
```

**Comment by Mrpolack** [comment]
You were right, i forced the changing version and now it worked.
Thanks man!
