### ISSUE TITLE
Heroku not working with the main app.

### ISSUE THREAD

**Issue by mrdiploben** [tiagorlampert/CHAOS#114]
[!] Error connecting with server: Get "http://172.19.35.122:13349/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[!] Error connecting on WS:  dial tcp 172.19.35.122:13349: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

2 errors given on heroku based server.

**Comment by supergarixd** [comment]
same is happening to me.

**Comment by mrdiploben** [comment]
@tiagorlampert 
Could we have some quick help please :D

**Comment by garix-png** [comment]
use this to fix it
https://github.com/tiagorlampert/CHAOS/issues/100
