### ISSUE TITLE
never connect

### ISSUE THREAD

**Issue by PolloMaxYT** [tiagorlampert/CHAOS#115]
If I use my laptop on the same network, it never connects (having antivirus and firewall turned off) to my virtual machine with chaos. But if I use the same computer where I have the virtual machine with chaos connect.
(The virtual machine at all times can receive and send pings to my laptop and vice versa)

**Comment by tiagorlampert** [comment]
Hello,

The generated client shows some error on the console?
Can you show how are you informing the connection params?
