### ISSUE TITLE
Unable to generate client

### ISSUE THREAD

**Issue by 05asans** [tiagorlampert/CHAOS#116]
When using Local Development, and already in the web page, when I Generate the client, an error pops up:

Failed building client binary. exit status 2:# github.com/tiagorlampert/CHAOS/client/app/handler app/handler/handler.go:68:28: undefined: any note: module requires Go 1.18 

Any solutions??

**Comment by tiagorlampert** [comment]
Looks like you are running a old golang version.

Make sure to run go 1.18 or greater.

To check your version run on terminal:

```bash
go version
```
