### ISSUE TITLE
Change first sentence of README

### ISSUE THREAD

**Issue by q2dg** [tiagorlampert/CHAOS#12]
Nowadays it says: "CHAOS Framework allow generate payloads and control remote machines."
I think it should say: CHAOS Framework allow generate payloads and control remote **Window systems**".
Thanks

**Comment by tiagorlampert** [comment]
Hi,
I will replace by "CHAOS Framework allow generate payloads and control remote **Windows systems**"

Thanks

**Comment by q2dg** [comment]
Thanks to you!!!
I close the issue, then.
