### ISSUE TITLE
Implement more options in shell

### ISSUE THREAD

**Issue by peterpt** [tiagorlampert/CHAOS#13]
Very limited options in the remote shell .
Execute option , screenshot , webcam list , webcam_stream options implemented could be interesting .
 
![chaos](https://user-images.githubusercontent.com/7487321/29240656-8e2d0018-7f37-11e7-9537-6e34cb31fa7a.png)

**Comment by tiagorlampert** [comment]
Hi!
Yes could be interesting implement this.
Feel free to implement that if you want.

Thanks for suggestions!

**Comment by NonElite** [comment]
I think he would've implemented it himself if he could've..

**Comment by tiagorlampert** [comment]
Yes, if I could have already implemented it.
_There are some projects to take screenshot and streaming webcam.
I need to check if they make available any packages so i can use the functionality, so i don't need to rewrite this._
Now I don't have much time to research how to implement this. I'm pretty busy with an academic project.
I'm sorry about that!

**Comment by tiagorlampert** [comment]
Hello,
After a long time some new improvements have been made.
