### ISSUE TITLE
How to remote ? C:

### ISSUE THREAD

**Issue by opferkind** [tiagorlampert/CHAOS#14]
so how to use CHAOS Framework allow generate payloads and control remote Windows systems ? just like the command or need to get FRamework too?

**Comment by krishnenduash** [comment]
at first install in kali  golang 
# apt-get install golang
then 
configure
in CAOS folder 

# go run CHAOS.go

**Comment by opferkind** [comment]
what u mean configure in cahos folder

**Comment by krishnenduash** [comment]
not configure CHAOS folder .
you configure golang path ok

**Comment by opferkind** [comment]
Cant u gute me something Details dont habe auch clientarea.php why

**Comment by opferkind** [comment]
Sry autocorrect.. 

I meant that can u explain step by step?

**Comment by tiagorlampert** [comment]
Hello!
To use CHAOS Framework, first do you have to install the dependencies, get a copy of repository and run CHAOS.
**Follow the next steps!**

To install the dependencies, run the command with administrator permissions:
`apt install golang upx-ucl -y`

Get a copy of repository:
`git clone https://github.com/tiagorlampert/CHAOS.git`

Go to folder cloned and run _CHAOS.go_:
`cd CHAOS`
`go run CHAOS.go`

**Video Demonstration:**
[Video - How to use](https://www.youtube.com/watch?v=QRNN2KwCYOg)
[CHAOS Framework Generate Payloads - by SSTec Tutorials](https://www.youtube.com/watch?v=8EJESyZJzb8)

**Comment by opferkind** [comment]
Lhost =enemy ip? 

*Port forwarding needed?

**Comment by tiagorlampert** [comment]
LHOST = **Your local IP**
LPORT = **Your local PORT** _8080_

**Comment by opferkind** [comment]
And how others get infectet with my IP?

**Comment by tiagorlampert** [comment]
The generated executable needs to be running on the other machine. He's going to connect with his machine.

**Comment by opferkind** [comment]
One More question how Do i copy the gdnerated exe

**Comment by tiagorlampert** [comment]
Hello, i'm sorry for the delay.
The executable is generated on CHAOS folder. You have to copy that manually for other system.
