### ISSUE TITLE
filemanager

### ISSUE THREAD

**Issue by Robiii97** [tiagorlampert/CHAOS#15]
Hello there.
I downloaded and installed chaos and it is awesome i really like to be able to download and upload file's from my home computer but it makes it really hard to typ the full path to the file. Will there be an option to view file lists in the future? That would make it so much easier.

**Comment by tiagorlampert** [comment]
Hi!
You can use `dir` command to list files in folder.

Example:
You can run this command to get the partitions name:
`powershell.exe get-psdrive -psprovider filesystem`

`dir c:\`

[Screenshot](http://i.imgur.com/lWMFkHf.png﻿)
