### ISSUE TITLE
How can I change directory?

### ISSUE THREAD

**Issue by NonElite** [tiagorlampert/CHAOS#16]
So I got a session open right now and when I type "dir" it shows me the directory, If I try to change it using something like cd C:\ or cd C:\\ or cd .. it stays the same, how do I move around? So that I can upload/download files to and from different paths
I guess I can download from different paths still, but I can't upload wherever I want
Please reply ASAP!
-Thanks!

**Comment by tiagorlampert** [comment]
Hello!
You can use `dir` or `tree` command to list folders and files in paths.
And to download and upload it is necessary that you inform the full path of the file.
Example:
You can run this command to get the partitions name:
`powershell.exe get-psdrive -psprovider filesystem`

`dir C:\Users\username`
`tree C:\Users\username`

[Screenshot](http://i.imgur.com/lWMFkHf.png﻿)

**Comment by NonElite** [comment]
that doesnt answer my question
I want to CHANGE directory, dir and tree list what's in the directory, if i want to upload a file, I specify the full path from my end and it gets uploaded to wherever directory the payload is opened

the question is how do i CHANGE directory, so for example do cd C:\ and after I do dir it should show all the files in the C:\ directory (cause I would have changed the dir), again dir and tree don't change it

**Comment by tiagorlampert** [comment]
I did the test here and it's working properly.
Remembering that you need administrative permissions to write in C:\Windows
Then run the executable generated as an administrator.

Follow a screenshot of the test:
![screen](https://user-images.githubusercontent.com/29933243/29618065-4000c924-87ed-11e7-8dab-daeeea55dc62.PNG)

**Comment by tiagorlampert** [comment]
I believe then this issue has been solved, i'll close it.
