### ISSUE TITLE
persistence failed

### ISSUE THREAD

**Issue by Robiii97** [tiagorlampert/CHAOS#17]
Chaos is working great is use it to transfer music and pictures from my nethunter phone to my desktop pc.
the only issue iam having is that it keeps saying persistence failed when i try to enable it and it also makes my command terminal all bugged it stops responding to commands and i must reinstall the payload for it to work again. I tried to disable persistence and reenable it but doesnt work

**Comment by tiagorlampert** [comment]
What is your version of Windows?

**Comment by Robiii97** [comment]
I tried it on multiple versions of windows 10 pro,home 64bit

**Comment by tiagorlampert** [comment]
Try run the executable generated as administrator.
Maybe it don't have permissions for do that.

What is the letter of the partition your Window is installed? _C?_

**Comment by Robiii97** [comment]
I aready tried administrator didnt work either.
yes it is c:/

**Comment by tiagorlampert** [comment]
I did the test here, and it's not working on Windows 10. CHAOS uses a method to install on startup that does not require administrative permissions, but it does not work in Windows 10.
The problem is that depending on how I change it to install it in initialization, it will be required to run always with administrative permissions.

The command to install at startup is as follows:
_**REG ADD HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /V "Microsoft Corporation" /t REG_SZ /F /D %SYSTEMDRIVE%\ProgramData\RANDOM\payload.exe**_

**I'll be seeing the best way to do this, so I'm going to update the code.**

Thanks for feedback!

**Comment by tiagorlampert** [comment]
While I do not update the code, you can copy the executable to the following path:

C:\Users\**USERNAME**\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by Robiii97** [comment]
Thanks alot. This project is awesome :)

**Comment by Robiii97** [comment]
Thank you.
will it take a while for the code to get updated?
and also what are your plans for the future? with this project? Will you add more features? Curious =)

**Comment by tiagorlampert** [comment]
About more functionalities.
https://github.com/tiagorlampert/CHAOS/issues/13

Now i'm pretty busy with academic project. But i'll update you as soon as i can.

**Comment by tiagorlampert** [comment]
Hello, i did the test again here on my Windows 10, and it's working. 
Do you could test again please?

_Check if you don't any antivirus on your system then can block the payload.
Ps: i have disabled Windows Defender on my system._

**Comment by Robiii97** [comment]
i got to test it on 1 machine and it worked.
also can you enable dns usage??
when i try it now it says invalid lhost it only accepts ip's

**Comment by tiagorlampert** [comment]
The way CHAOS works, i can't implement it.
You can only use IP address.

**Comment by NonElite** [comment]
just edit the code instead of limiting to 15 characters make it like 50 and then you can use a hostname dns instead of an ip

**Comment by tiagorlampert** [comment]
Hello, 
I was seeing the [documentation](https://golang.org/pkg/net/#pkg-overview) and it seems that passing the hostname in the IP place is to work, like you said. But I couldn't test it.
Did you get a test to see if it works?

**Comment by tchach0** [comment]
[?] The information above is correct? (y/n): y

 [*] Compiling...
 [!] File not found! There's a problem with compiling.

 [i] Press [ENTER] key to continue...

**Comment by tiagorlampert** [comment]
Did you get all dependencies?
Make sure to follow all steps. https://github.com/tiagorlampert/CHAOS#how-to-install

**Comment by tchach0** [comment]
i try all step by step but when i try to make generate ................ -- windows 


?] The information above is correct? (y/n): y

[*] Compiling...
[!] File not found! There's a problem with compiling.

[i] Press [ENTER] key to continue...

**Comment by tchach0** [comment]
go get golang.org/x/sys/windows
this cmd not run

**Comment by tiagorlampert** [comment]
Could you send a screenshot?
Do you have installed all the dependencies described in [README?](https://github.com/tiagorlampert/CHAOS#how-to-install)

**Comment by tiagorlampert** [comment]
I'm closing this old issue.
If the problem persist, please open a new issue.
