### ISSUE TITLE
Domain Name as LHOST Not Working?

### ISSUE THREAD

**Issue by H3XK4l1** [tiagorlampert/CHAOS#18]
How do I enable that? do I edit the code myself if so tell me what to edit.

**Comment by tiagorlampert** [comment]
Hello, It's working only with IP at the moment.

I was seeing the documentation and it looks like you just need to pass the domain name in place of the IP to work. Follow the documentation link [Package net](https://golang.org/pkg/net/#pkg-overview) .
To pass the name you need to remove code validation, which are the marked lines (1) in the screenshot.
**If it works, I'll update the code.**
_I don't have a domain to test, i tested it locally but it didn't work._

![ScreenShot](https://user-images.githubusercontent.com/29933243/31020149-845262d0-a508-11e7-80f3-a390ee41968b.PNG)

**Comment by H3XK4l1** [comment]
Because I need to put this domain in LHOST h3xk4l1.ddns.net
But I don't know how to porperly edit the code.

**Comment by tiagorlampert** [comment]
To edit the source code, open the file _CHAOS.go_ with text editor and delete the follow selected lines in screenshot. Doing this you can put your domain.

![Screenshot](https://user-images.githubusercontent.com/29933243/31091674-268841e8-a782-11e7-953f-d0fff7414d81.PNG)

**Comment by H3XK4l1** [comment]
Thank you so much.I will close this issue now.
