### ISSUE TITLE
Interrupt command instead of  killing CHAOS with ^C.

### ISSUE THREAD

**Issue by ghost** [tiagorlampert/CHAOS#19]
It would be really nice if ^C interrupted an ongoing command in the obtained shell instead of killing CHAOS. Using CHAOS to run a psempire stager makes it further unusable even after the exe has been executed, rendering the CHAOS session useless(and if the launched stager fails too, the access to the machine is lost altogether)
I dont know much about this stuff but I think ^C should provide a fresh prompt instead of waiting for the previous thing to be completed.
PS: btw love your work CHAOS has been my goto since a few days..

**Comment by tiagorlampert** [comment]
No longer required singe we have a UI web version.
