### ISSUE TITLE
encode

### ISSUE THREAD

**Issue by Qurexhi** [tiagorlampert/CHAOS#2]
which encode you use in output file base64 or Xor? please explain the encryption process

**Comment by tiagorlampert** [comment]
I use Base64. First i'm generating a file, then i encrypt it with AES and encode the result with Base64.
I'm saving the Key and the Base64 Output in constants in the final file. That will be decrypted at runtime, writing a file to Temp.

**Comment by Qurexhi** [comment]
Hmm Nice so can we FUD custom exe by using this method?

**Comment by tiagorlampert** [comment]
Yes, is possible. But some AV can detect using heuristic methods. And i have to write the file to run the code. So using this method is more effective to scans. Norton Antivirus is blocking the payload.

**Comment by Qurexhi** [comment]
thanks bro can you tell me how to change output go file with custom exe base64?

**Comment by tiagorlampert** [comment]
I write a example. You can pass a file to encode.

https://gist.github.com/tiagorlampert/89815835376527b1f90f659246301afd

**Comment by Qurexhi** [comment]
Great bro but its FUD scantime and runtime AVs are detect the virus. any solution to make it runtime FUD?
