### ISSUE TITLE
Installed golang still go: command not found

### ISSUE THREAD

**Issue by PulkitSingh256** [tiagorlampert/CHAOS#20]
I know it's not the issue of this tool but maybe you guys can help.
I installed the golang but still it's showing go command not found

**Comment by tiagorlampert** [comment]
What is your operating system?

**Comment by PulkitSingh256** [comment]
Kali Linux 2016.2

**Comment by tiagorlampert** [comment]
Run on terminal:
`go env`

And send me output.

**Comment by PulkitSingh256** [comment]
root@kali:~# go env
bash: go: command not found
root@kali:~#

**Comment by tiagorlampert** [comment]
It will not work if golang is not configured correctly.

Try reinstall golang.

Run as root:
`apt update && apt install golang`

Case get some error, please send me the output.

**Comment by krishnenduash** [comment]
apt install golang -y

**Comment by PulkitSingh256** [comment]
I have installed golang and after that I am running this command go env
`rook@kali:~# go env
bash: go: command not found
root@kali:~#`
[https://imgur.com/a/ykkYQ](url)

**Comment by tiagorlampert** [comment]
Do you have your OS upgraded?
That's some bug on kali probably, if not solve the problem upgrading your system, try reinstall.

**Comment by PulkitSingh256** [comment]
Maybe

**Comment by PulkitSingh256** [comment]
Nobody else had it

**Comment by tiagorlampert** [comment]
You can try set GOPATH.
Moment..

**Comment by PulkitSingh256** [comment]
Guide me please

**Comment by tiagorlampert** [comment]
Run 
`ls /usr/lib/go-1.8`
And send me output.

**Comment by PulkitSingh256** [comment]
There are folders
bin, doc, pkg, src, test VERSION AND A favicon.ico.gz

**Comment by PulkitSingh256** [comment]
I am able to run go in bin by ./go

**Comment by tiagorlampert** [comment]
Ok.
Run
`export GOROOT="/usr/lib/go-1.8"`

**Comment by PulkitSingh256** [comment]
Did

**Comment by tiagorlampert** [comment]
Run `go` on terminal. Works?

**Comment by PulkitSingh256** [comment]
Nope

**Comment by tiagorlampert** [comment]
Lol wtf

**Comment by PulkitSingh256** [comment]
See this image 
[https://imgur.com/a/lGrTg](url)

**Comment by tiagorlampert** [comment]
`export GOROOT="/usr/lib/go-1.8"`

without /bin

**Comment by PulkitSingh256** [comment]
Yes after seeing that I have mistakenly added bin, I removed bin and then tried still not working

**Comment by PulkitSingh256** [comment]
I am able to run chaos by changing directory to /use/lib/go-1.8/bin 
And then running ./go run /root/Desktop/CHAOS.go

**Comment by PulkitSingh256** [comment]
But go is not able to make exe it gives error

**Comment by tiagorlampert** [comment]
Probably it give errors cause need environment variables configured like that:
![Variables](https://user-images.githubusercontent.com/29933243/31558915-23076534-b025-11e7-879e-afa8c7617b81.PNG)

You can set using `export` before:
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build786735881=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by PulkitSingh256** [comment]
I have all same settings

**Comment by PulkitSingh256** [comment]
I have a folder go and go-1.7 should I delete them

**Comment by mateo24xx** [comment]
i have the same problem..i dont understand because i had CHAOS it work perferct then i deleted because i had not enough space in my disk ...then aftercouple day's i download it again and now when i want to run it ,i have this strange message .." bash: go: command not found "

**Comment by PulkitSingh256** [comment]
I finnaly had to change my os. I found no solution

**Comment by tiagorlampert** [comment]
@mateo24xx 
When this occurs normally is because the Golang is not installed or the GOROOT is not set correctly. I don't know why this is happening, but the recommended would be reinstall Golang, if it does not resolve is probably some problem in the OS.

**Comment by godmarvin** [comment]
maybe not permission to execute the .sh file;
commend:```ll ``` and find the file or directory  permissions

**Comment by aboutqx** [comment]
After set GOROOT,you also need `export PATH=$PATH:$GOROOT/bin`,then it will execute from `PATH`

**Comment by rams3sh** [comment]
Had same problem and this solution worked for me. This solution is specific to Kali Linux and works only if you have installed golang using apt package manager as the uninstall commands used below are dependent on apt based installation of golang.

1. First uninstall the current installation of golang.

apt-get purge golang

2. Clean up your apt caches and remove all unwanted left out dependencies of the golang which has not been uninstalled. I stacked up all housecleaning apt commands in there to ensure , there is no leftovers.

apt-get autoclean
apt-get autoremove
apt-get clean
apt-get remove

3. Install golang
apt-get install golang

Try out typing "go version" to check if it is installed correctly
Hope this solution works.

**Comment by dactoankmapydev** [comment]
> After set `GOROOT`,you also need `export PATH=$PATH:$GOROOT/bin`,then it will execute from `PATH`.
> It works for me,on ubuntu 20.

**Comment by seqrity** [comment]
You can do the following steps for install:

`sudo apt-get install golang`
`git clone https://github.com/tomnomnom/httprobe.git`
`cd httprobe`
`go build main.go`
`mv main httprobe`
Help:
`./httprobe -h`

Ref: https://www.youtube.com/watch?v=OoK-CGFjYXY

**Comment by tiago-peres** [comment]
I've gone through the same problem and in my case the problem was with the go `.tar.gz` I've used.

So, to install Go, started by running

    curl -O https://dl.google.com/go/go$VERSION.linux-amd64.tar.gz

OR

    curl -O https://dl.google.com/go/go$VERSION.linux-386.tar.gz

I tested first with `...-386.tar.gz` but then kept getting 

> /usr/local/go/bin/go: No such file or directory.

then eventually it worked fine with

    curl -O https://dl.google.com/go/go1.16.6.linux-amd64.tar.gz

**Comment by ELBEQQAL94** [comment]
> apt install golang -y
> 
> work perfect

Thanks for help

**Comment by nidsydv1202** [comment]
hiiii,

**Comment by nidsydv1202** [comment]
In my case, there is go is installed and go path is set. But When I am installing the chaincode it gives the error.

**Comment by dyappscrip** [comment]
try exporting env in local terminal 
`export PATH=$(go env GOPATH)/bin:$PATH`

**Comment by Asef264** [comment]
try this : 
export PATH=$PATH:/usr/local/go/bin
