### ISSUE TITLE
Strange runtime error runnig CHAOS

### ISSUE THREAD

**Issue by akki9711** [tiagorlampert/CHAOS#22]
I use CHAOS frequently but today when i run CHAOS, it came up with strange runtime error message attached below. I run it on KALI LINUS 2017 which is up-to-date. please help.
Thanks

![screenshot from 2017-10-25 11-43-16](https://user-images.githubusercontent.com/29523549/31983105-79fa7928-b979-11e7-9eae-c79acc5d4226.png)

**Comment by tiagorlampert** [comment]
It's probably a problem in your installation of Golang. (maybe something was corrupted)

Run in the terminal `go env` and send me output.

Did you try to reinstall golang?

**Comment by akki9711** [comment]
on running "go env" it got the following -
![screenshot from 2017-10-28 11-32-27](https://user-images.githubusercontent.com/29523549/32131741-6b98231a-bbd3-11e7-9dc0-d9fe3497af76.png)

**Comment by tiagorlampert** [comment]
I think maybe your GOROOT is wrong. Or another environment variable.

You can set using 
`export GOROOT="/usr/lib/go-1.8"`

_Check if `/usr/lib/go-1.8` exist._

![ScreenShot](https://user-images.githubusercontent.com/29933243/32138410-f8468198-bc10-11e7-8bcf-83128448d264.PNG)

**Comment by akki9711** [comment]
Thanks  @tiagorlampert for the solution. it seems to fix the problem but it is not permanent.
after running " export GOROOT="/usr/lib/go-1.8" CHAOS works normal but as soon as i exit the terminal and start CHAOS it again shows that error and GOROOT directory is set to default.
how can i permanently set it to "/usr/lib/go-1.8"

**Comment by tiagorlampert** [comment]
You can try add this lines in your `.bashrc` file.

`nano ~/.bashrc`

And add this lines in the end.

```
export GOROOT="/usr/lib/go-1.8"
export PATH=$PATH:$GOROOT
```

Something like this.
![Screenshot](https://user-images.githubusercontent.com/29933243/32145514-19b9a116-bcb1-11e7-8c13-eb7c11443b7a.PNG)

**_Done this, every time you login will be exported that variable.
When you change the version of Golang you will have to update the export path._**
