### ISSUE TITLE
Screenshot sometimes gets stuck at getting screenshot

### ISSUE THREAD

**Issue by usama7628674** [tiagorlampert/CHAOS#25]
Screenshot works but sometimes it gets stuck at **Getting Screenshot** and I can't use it.I have to close the terminal and re-execute the (.exe) on the victim pc to get it work again.

**Comment by tiagorlampert** [comment]
Hello,
A know issue is the screenshot crash if the screen is locked.
I corrected a process on screenshot that leaves the payload busy by a moment on victim side.
If you maybe can clone CHAOS again and test it.
Check in what situation the payload crash, if the system are suspended, screen locked or something like that.

**Comment by usama7628674** [comment]
@tiagorlampert Thanks for your reply.I'll reclone and try again tomorrow and report back.I'll attach screenshot here if the payload will crash again.

**Comment by usama7628674** [comment]
![152334352311518163](https://user-images.githubusercontent.com/29252277/38540693-35eb37b6-3cb6-11e8-8941-fdfeeccb7cbd.png)

It worked 2 times as in the screenshot but third time it gets stuck.On victim side is watching a youtube video.

**Comment by tiagorlampert** [comment]
I did test here and it worked more than two times. I really don't know what can be happening on your machine. Probably it should be taking longer than normal to take and send the screenshot.

**Comment by usama7628674** [comment]
It's random.Sometimes it's stuck after taking more than 2 screenshots.

**Comment by tiagorlampert** [comment]
Hello,
This issue is very old. Could you try again with the new version, and send me a feedback?

**Comment by usama7628674** [comment]
@tiagorlampert Okay I'll try in a few days and report back.

**Comment by tiagorlampert** [comment]
I'm closing this old issue.
If the problem persist, please open a new issue.
