### ISSUE TITLE
Multiple connections?

### ISSUE THREAD

**Issue by chithone** [tiagorlampert/CHAOS#27]
what is i run the payload on several of my Vms, how to do i listen to them one after the other without loosing connection?

**Comment by tiagorlampert** [comment]
Hello,
At the moment the CHAOS doesn't support multiple connections.
I'll mark it to futures enhancements.

**Comment by chithone** [comment]
ok thanks

**Comment by tiagorlampert** [comment]
Hi @chithone,
After a long time, CHAOS now have support to multiple connections!! :tada::tada:

Could you try it?!
