### ISSUE TITLE
Issues running executable on Windows 10

### ISSUE THREAD

**Issue by nicholasb2101** [tiagorlampert/CHAOS#29]
I have all of CHAOS and it's dependencies installed properly but when i open the created executable on a windows computer (running windows 10) it states:

> Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

and then as soon as i press okay the file deletes itself. Has anyone had this issue or found a fix for it? FYI I'm running CHAOS 2.5.0 if that helps at all.

**Comment by Odka33** [comment]
Bloquer par l'antivirus

**Comment by tiagorlampert** [comment]
Hello @nicholasb2101,
Probably your antivirus is removing the CHAOS payload, try disable the antivirus or antispyware.

**Comment by tiagorlampert** [comment]
Hello,
I've think this issue has been solved, i'm closing it.
