### ISSUE TITLE
go tool: no such tool "compile"

### ISSUE THREAD

**Issue by adminlinzi** [tiagorlampert/CHAOS#3]
root@kali:/opt# git clone https://github.com/tiagorlampert/CHAOS
Cloning into 'CHAOS'...
remote: Counting objects: 28, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 28 (delta 11), reused 28 (delta 11), pack-reused 0
Unpacking objects: 100% (28/28), done.
root@kali:/opt# apt install golang upx-ucl -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
golang is already the newest version (2:1.7~5).
golang set to manually installed.
upx-ucl is already the newest version (3.91-4).
upx-ucl set to manually installed.
The following packages were automatically installed and are no longer required:
  dkms jsql libjs-mochikit linux-headers-686-pae open-vm-tools-dkms
  python-advancedhttpserver python-alembic python-boltons python-cheetah
  python-dap python-editor python-formencode python-geoip2 python-geojson
  python-icalendar python-maxminddb python-mpltoolkits.basemap python-openid
  python-pampy python-paste python-pastedeploy python-pastedeploy-tpl
  python-pastescript python-pluginbase python-pyotp python-scgi
  python-smoke-zephyr python-tempita python-termcolor python-tzlocal
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 247 not upgraded.
root@kali:/opt# cd CHAOS
root@kali:/opt/CHAOS# go run CHAOS.go
go tool: no such tool "compile"

root@kali:/opt/CHAOS# cat /etc/issue
Kali GNU/Linux Rolling \n \l
root@kali:/opt/CHAOS# uname -a
Linux kali 4.9.0-kali4-686-pae #1 SMP Debian 4.9.30-1kali1 (2017-06-06) i686 GNU/Linux

**Comment by tiagorlampert** [comment]
Run:
`
go env
`

And send me output.

Probably your GOROOT is incorrect.

**Comment by adminlinzi** [comment]
root@kali:~# whoami 
root
root@kali:~# go env
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build143117457=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
root@kali:~# 

@tiagorlampert

**Comment by tiagorlampert** [comment]
Based on your output: `golang is already the newest version (2:1.7~5).` You have installed Go version 1.7

You can check version running:
`go version`

My output:
`tiagorlampert@host:~$ go version
go version go1.8.3 linux/amd64
`
Maybe you have to change the GOROOT.
Try:
`export GOROOT=/usr/lib/go`
or
`export GOROOT="/usr/lib/go-1.8"` - Check your Golang version, in my case 1.8.

Case nothing work, try update your OS:
`apt update && apt dist-upgrade -y`

**Comment by tiagorlampert** [comment]
Hi, case your problem don't have be solved, you can try clone CHAOS again, and run a version compiled.

`git clone https://github.com/tiagorlampert/CHAOS.git`
`sudo chmod +x CHAOS`
`./CHAOS`

**Comment by adminlinzi** [comment]
root@kali:~# go version
go version go1.7.4 linux/386

maybe my kali has a bug .
I will reinstall the system
thanks @tiagorlampert
