### ISSUE TITLE
can't generated test.exe. Just generated test.go

### ISSUE THREAD

**Issue by tankexia007** [tiagorlampert/CHAOS#30]

**Comment by tankexia007** [comment]
[*] Enter LHOST: 192.168.159.137
 [*] Enter LPORT: 4402
 [*] Enter name for file (.exe): 123

 [*] Compiling...
 [*] Generated "123.exe"

but there is not 123.exe . I can't found 123.exe anywhere. 
just there is the 123.go

**Comment by tiagorlampert** [comment]
Hello,
Do you installed the dependencies?
You must have the dependencies installed to generate the .exe file.

**Get and install external imports (requirement to screenshot)**
_$ go get github.com/kbinani/screenshot && go get github.com/lxn/win
$ go install github.com/kbinani/screenshot && go install github.com/lxn/win_

Check, [How to use](https://github.com/tiagorlampert/CHAOS#how-to-use)

**Comment by tiagorlampert** [comment]
Hello,
I've think this issue has been solved, i'm closing it.
