### ISSUE TITLE
screenshot requirement failed

### ISSUE THREAD

**Issue by ahmedrik** [tiagorlampert/CHAOS#31]
one of the requirement for the screenshot : 
go get github.com/kbinani/screenshot

is failing and giving the following error

can't load package: package github.com/lxn/win: build constraints exclude all Go files in /home/tesla/go/src/github.com/lxn/win

Now i am using ParrotOS but i dont think that may be an issue as by looking at it, it looks more of package error. I did check the link and github is working

**Comment by tiagorlampert** [comment]
Hello, sorry for delay.
It's a problem with dependencies.

I did a video tutorial of how install. Check it iout [https://www.youtube.com/watch?v=Fq_0yDPFjYE](https://www.youtube.com/watch?v=Fq_0yDPFjYE)

Could you try again? I've updated CHAOS to a new release, the requirements are been changed.
Follow [How To Install](https://github.com/tiagorlampert/CHAOS#how-to-install)

**Comment by tiagorlampert** [comment]
Hello, i think this problem has been solved. If the problem keep open a new issue. I'm closing it.
