### ISSUE TITLE
Problem while installing golang. cant fetch some hash file  

### ISSUE THREAD

**Issue by die-dimitry** [tiagorlampert/CHAOS#32]

**Comment by itz-8infinite** [comment]
(appstreamcli:9243): GLib-CRITICAL **: 13:59:45.767: g_atomic_ref_count_dec: assertion 'g_atomic_int_get (arc) > 0' failed
Reading package lists... Done
E: Failed to fetch http://ftp.yzu.edu.tw/Linux/kali/dists/kali-rolling/main/source/Sources.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:12385945 [weak]
    - SHA256:c926cb8e9ca272fd72ad2a90b50759f92a16dffa5e820a0568a19ff52d7009c3
    - SHA1:9ff294d80e3d11b6e7c41d9f9370e701393807ce [weak]
    - MD5Sum:a6ac820c3355bceb45eefa68c2f309e0 [weak]
   Hashes of received file:
    - SHA256:40c8dd1118c976a2a8613f6aced8123bfe86737b907342b0e68e875738f3f769
    - SHA1:8e4fa06c74a132c4ca35a5d465aca08f08aecd36 [weak]
    - MD5Sum:7ff8a5587e0a3bb4326f5d647fd4fc7e [weak]
    - Filesize:12385945 [weak]
   Last modification reported: Sun, 02 Dec 2018 00:03:35 +0000
   Release file created at: Sun, 02 Dec 2018 00:04:30 +0000
W: Failed to fetch http://ftp.yzu.edu.tw/Linux/kali/dists/kali-rolling/non-free/source/Sources.gz  
E: Failed to fetch http://ftp.yzu.edu.tw/Linux/kali/dists/kali-rolling/main/binary-i386/Packages.gz  
E: Failed to fetch http://ftp.yzu.edu.tw/Linux/kali/dists/kali-rolling/main/binary-amd64/Packages.gz  
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by tiagorlampert** [comment]
Hello,
I'm sorry for delay.
It's weird, would you try it again, with the new update and requirements?
Follow, [https://github.com/tiagorlampert/CHAOS#how-to-install](https://github.com/tiagorlampert/CHAOS#how-to-install)

**Comment by tiagorlampert** [comment]
I'm closing this old issue.
If the problem persist, please open a new issue.
