### ISSUE TITLE
create only .go

### ISSUE THREAD

**Issue by arab228** [tiagorlampert/CHAOS#34]
Create only .go ! 
~$ go get github.com/kbinani/screenshot
~$ go get github.com/lxn/win
can't load package: package github.com/lxn/win: build constraints exclude all Go files in /home/ivan/go/src/github.com/lxn/win
~$ go install github.com/kbinani/screenshot
~$ go install github.com/lxn/win
can't load package: package github.com/lxn/win: build constraints exclude all Go files in /home/ivan/go/src/github.com/lxn/win
I installed but dont working (

**Comment by Alpha9807** [comment]
I have the same problem

**Comment by Terriblewind** [comment]
+

**Comment by Terriblewind** [comment]
i have the same problem too

**Comment by tiagorlampert** [comment]
Hello guys, sorry for delay.
It's a problem with dependencies.

Wich OS are you been running?
I did a video tutorial of how install. Check it iout [https://www.youtube.com/watch?v=Fq_0yDPFjYE](https://www.youtube.com/watch?v=Fq_0yDPFjYE)

Could you try again? I've updated CHAOS to a new release, the requirements are been changed.
Follow [How To Install](https://github.com/tiagorlampert/CHAOS#how-to-install)

**Comment by Terriblewind** [comment]
Thank you so much!

**Comment by arab228** [comment]
Thank you! It work!!
