### ISSUE TITLE
error when use go get golang.org/x/sys/windows

### ISSUE THREAD

**Issue by shadihh9** [tiagorlampert/CHAOS#36]
package golang.org/x/sys/windows: unrecognized import path "golang.org/x/sys/windows" (parse https://golang.org/x/sys/windows?go-get=1: no go-import meta tags ())

**Comment by tiagorlampert** [comment]
When you try compiling the payload, what's your output error?

**Comment by shadihh9** [comment]
i use this command before run tool go get golang.org/x/sys/windows

**Comment by shadihh9** [comment]
and also when use command dont run the tool go run main.go

**Comment by shadihh9** [comment]
i use git clone to download tool but dont run the tool idont know

**Comment by tiagorlampert** [comment]
Which OS are you been using?
Could you send me a screenshot of error message? It's better to understand in which step the errors happen.

**Comment by shadihh9** [comment]
kail linux 2019
[!] File not found! There's a problem with compiling. ../go/src/github.com/lxn/win/advapi32.go:10:2: cannot find package "golang.org/x/sys/windows" in any of:
	/usr/lib/go-1.11/src/golang.org/x/sys/windows (from $GOROOT)
	/root/go/src/golang.org/x/sys/windows (from $GOPATH)

**Comment by shadihh9** [comment]
https://imgur.com/a/wI4CMwk

**Comment by shadihh9** [comment]
im sorry i cause error closed im not need close the issues
