### ISSUE TITLE
error when use go get golang.org/x/sys/windows

### ISSUE THREAD

**Issue by shadihh9** [tiagorlampert/CHAOS#37]
kail linux 2019
[!] File not found! There's a problem with compiling. ../go/src/github.com/lxn/win/advapi32.go:10:2: cannot find package "golang.org/x/sys/windows" in any of:
/usr/lib/go-1.11/src/golang.org/x/sys/windows (from $GOROOT)
/root/go/src/golang.org/x/sys/windows (from $GOPATH)
https://imgur.com/a/wI4CMwk

**Comment by shadihh9** [comment]
please help me

**Comment by tiagorlampert** [comment]
Hello,
Do you have installed all dependencies described in [readme](https://github.com/tiagorlampert/CHAOS#how-to-install)?

Probably are missing _golang.org/x/sys/windows_.
Run: `go get golang.org/x/sys/windows`

**Comment by shadihh9** [comment]
i use this code  go get golang.org/x/sys/windows and i have error  package golang.org/x/sys/windows: unrecognized import path "golang.org/x/sys/windows" (parse https://golang.org/x/sys/windows?go-get=1: no go-import meta tags ())

**Comment by tiagorlampert** [comment]
Hello,
I've updated the dependencies manager. Could you try again using the new way?
Follow all steps described in readme (the package dependencies are been changed). [https://github.com/tiagorlampert/CHAOS#how-to-install](https://github.com/tiagorlampert/CHAOS#how-to-install)

Maybe, you could try updated you OS to the last version. I think it should be an issue with your OS.

**Comment by shadihh9** [comment]
when i use the code dep ensure error message  grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export golang.org/x/sys: unable to deduce repository and source type for "golang.org/x/sys": unable to read metadata: unable to parse go-import metadata: XML syntax error on line 9: expected /> in element

**Comment by tiagorlampert** [comment]
Have you tried to reinstall your golang?

**Comment by dustindog101** [comment]
i get the same error wih dep ensure

**Comment by GUGID** [comment]
I get that error too, but only on one of my computer. The other
 one works fine, so I copy the file golang.org/x/sys to the location which could be any of the paths where your compiler couldn't find the package. Here is the golang package. Maybe this could work.
 [golang.org.zip](https://github.com/tiagorlampert/CHAOS/files/4603469/golang.org.zip)

**Comment by peteryuanpan** [comment]
> I get that error too, but only on one of my computer. The other
> one works fine, so I copy the file golang.org/x/sys to the location which could be any of the paths where your compiler couldn't find the package. Here is the golang package. Maybe this could work.
> [golang.org.zip](https://github.com/tiagorlampert/CHAOS/files/4603469/golang.org.zip)

Thanks very much for you .zip. It works!

**Comment by tiagorlampert** [comment]
I'm closing this old issue.
If the problem persist, please open a new issue.
