### ISSUE TITLE
Listen

### ISSUE THREAD

**Issue by username836** [tiagorlampert/CHAOS#39]
When I turn on the listener the victim opens and run the exe but nothing happens it keeps listening on port 444

**Comment by tiagorlampert** [comment]
Hello,
Could you check if don't  have any firewall or antivirus blocking the connection.
Or check if port are correct when you generated the executable.

**Comment by m4dmeds** [comment]
I have the same problem. When I entered the command “listen lport=3333” it is displaying “waiting for connection on port 3333” (I have run the .exe file on Windows ).

**Comment by tiagorlampert** [comment]
I'm closing this old issue.
If the problem persist, please open a new issue.
