### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by bffaulkner1987** [tiagorlampert/CHAOS#40]
[*] Compiling...
 [!] File not found! There's a problem with compiling. build/Windows/chaos.exe/chaos.exe.go:16:2: cannot find package "github.com/kbinani/screenshot" in any of:
	/usr/lib/go-1.11/src/github.com/kbinani/screenshot (from $GOROOT)
	/root/go/src/github.com/kbinani/screenshot (from $GOPATH)
build/Windows/chaos.exe/chaos.exe.go:17:2: cannot find package "github.com/matishsiao/goInfo" in any of:
	/usr/lib/go-1.11/src/github.com/matishsiao/goInfo (from $GOROOT)
	/root/go/src/github.com/matishsiao/goInfo (from $GOPATH)

I followed the install instructions and this is the error i get when trying to compile a windows executable. Any help would be appreciated, Thanks.

**Comment by tiagorlampert** [comment]
Some dependencies are not installed, then it can't compile and generate the executable.

You need `go-dep` package installed on your OS. `sudo apt install go-dep`.
Run `dep ensure` to get the dependencies.

All the process are described in [https://github.com/tiagorlampert/CHAOS#how-to-install](https://github.com/tiagorlampert/CHAOS#how-to-install).

**Comment by tiagorlampert** [comment]
Hello, could you try again with the latest version of CHAOS?

I'm closing this old issue.
If the problem persist, please open a new issue.
