### ISSUE TITLE
Mutiple Issues

### ISSUE THREAD

**Issue by ghost** [tiagorlampert/CHAOS#44]
So this software is great but im having a few issues. On issue is that my screenshots only take the top left corner. My second issue is that with cmd it only comes up for a second with the Microsoft Windows [Version 10.0.18362.356]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\USERNAME\Downloads>
thing then disapears. last I cant surf around in the files. 
Any help will be appreciated.

**Comment by tiagorlampert** [comment]
I'm closing this old issue.
If the problem persist, please open a new issue.
