### ISSUE TITLE
no such file directory

### ISSUE THREAD

**Issue by azamet90** [tiagorlampert/CHAOS#47]
azamet@MrRobots  ~  go get github.com/tiagorlampert/CHAOS
 azamet@MrRobots  ~  cd ~/go/src/github.com/tiagorlampert/CHAOS
bash: cd: /home/azamet/go/src/github.com/tiagorlampert/CHAOS: no such file directory

**Comment by tiagorlampert** [comment]
Could you try with the latest version following the [How to install](https://github.com/tiagorlampert/CHAOS#how-to-install)?

I'm closing this old issue.
If the problem persist, please open a new issue.
