### ISSUE TITLE
Error building binary! exit status 1

### ISSUE THREAD

**Issue by badboycxcc** [tiagorlampert/CHAOS#50]
Error building binary! exit status 1 ，windows and linux
![image](https://user-images.githubusercontent.com/72059221/102996605-5b8ad680-455e-11eb-9934-5e0a70d88cd0.png)
![image](https://user-images.githubusercontent.com/72059221/102996700-85dc9400-455e-11eb-91a7-519261d409b5.png)

**Comment by tiagorlampert** [comment]
Hello,
I've made a little update and added a build error logging. #51

Could you update your CHAOS version and try again?
Than we can see what error you got to solve this issue.
