### ISSUE TITLE
How to using Chaos with Ngrok?

### ISSUE THREAD

**Issue by rasothecoder** [tiagorlampert/CHAOS#52]
Hi i want to using Chaos with Ngrok how i can? Please help me tiagor.

**Comment by rasothecoder** [comment]
Please help i can't connect target computer when im using ngrok.

**Comment by tiagorlampert** [comment]
Could you try again with the latest version?
Officially i didn't tested ngrok, but if you can't connect using the latest version i'll take a look on how to make work.

**Comment by phanthuthao** [comment]
Please help me, i can't connect target computer when im using ngrok.

**Comment by tiagorlampert** [comment]
Hello,

I added a easy way to deploy on heroku.
Can you guys try?

I think is more easy than ngrok.

The process are described on Readme:
[https://github.com/tiagorlampert/CHAOS#3-deploy-on-heroku](https://github.com/tiagorlampert/CHAOS#3-deploy-on-heroku)
