### ISSUE TITLE
I cant upload any file

### ISSUE THREAD

**Issue by manstanman** [tiagorlampert/CHAOS#58]
I cant upload a file
To upload the file I use : upload route/file
Example: upload /home/kali/Desktop/file.txt and dont upload u.u
Sorry for being such a novice
Attached is a photo
And sorry for my english
![Screenshot_2021-06-25_22_14_50](https://user-images.githubusercontent.com/86705969/123914880-e4d7f700-d94d-11eb-952d-4fd589f3c326.png)

**Comment by tiagorlampert** [comment]
Hello @manstanman,
Could you try again using the latest version with web UI support?
