### ISSUE TITLE
change default user/password of web manager?

### ISSUE THREAD

**Issue by nobeltnium** [tiagorlampert/CHAOS#63]
Hi, are there a way to change the default user/password for the web based manager? I took a glance at the source code but can't find a variable for that (i don't speak GO really, so may be i'm missing a spot or two).

**Comment by tiagorlampert** [comment]
Hello, yes there is.

**1.** Go to user profile.

![image](https://user-images.githubusercontent.com/29933243/133614065-7e9bf0da-a899-4b32-904a-59010ca068d6.png)

**2.** Inform the current and new password.

![image](https://user-images.githubusercontent.com/29933243/133614206-f5403f89-4f1b-4b46-90c0-cd147bfad32c.png)

**Comment by nobeltnium** [comment]
i can't believe i missed that hahaha. Thanks for replying so fast. And great work btw <3 <3 <3
