### ISSUE TITLE
File Delete / Uninstall Apps

### ISSUE THREAD

**Issue by PowerX-NF** [tiagorlampert/CHAOS#67]
Hey tiagorlampert, 
I wish you could add this feature where I can be able to uninstall apps and delete files from remote systems

**Comment by tiagorlampert** [comment]
Hi @PowerX-NF,

Now we have a option to delete files from the File Explorer available on the latest version.

![image_2022-02-15_00-31-23](https://user-images.githubusercontent.com/29933243/153987690-8ec84137-4e26-4d99-84a8-ae6f3a3677f3.png)
