### ISSUE TITLE
Ideas for CHAOS

### ISSUE THREAD

**Issue by peterpt** [tiagorlampert/CHAOS#7]
I have some ideas for CHAOS that you can iplement in the future if you want .

1st - Create switches on chaos 

This means if user wants to create a backdoor without having to stop on every option all he/she have to do is to invoke the switches .

ex : ./chaos --g --lhost 1.1.1.1 --lport 7777 --exe testfile.exe
-g=generate

To generate these switches all you have to do  is put some if statements at the start of your script .
$0 = --g
$1= --lhost
$2= ip
etc ....
In bash is easy to do , but in go i have no idea .

2nd - Create interface with metasploit framework listeners (i do not think if it is possible) , but it would be a nice idea if implemented .

**Comment by tiagorlampert** [comment]
Hi, thanks for the ideas. Maybe in the future i will implement something.
