### ISSUE TITLE
Changing it to WAN

### ISSUE THREAD

**Issue by Nabeel-javed** [tiagorlampert/CHAOS#70]
is it possible to change it to WAN because it works using local IP address, so is there any way possible to change it to WAN so that we can use it over the all internet

**Comment by tiagorlampert** [comment]
Hello,
Yes, it can. Can be deployed on any server, just need to setup the correct port on environment variables.

I added a easy way to deploy on heroku.
Can you try?

The process are described on Readme:
[https://github.com/tiagorlampert/CHAOS#3-deploy-on-heroku](https://github.com/tiagorlampert/CHAOS#3-deploy-on-heroku)
