### ISSUE TITLE
how can we change it to work on WAN

### ISSUE THREAD

**Issue by Nabeel-javed** [tiagorlampert/CHAOS#71]

**Comment by tiagorlampert** [comment]
Hello,
Yes, it can. Can be deployed on any server, just need to setup the correct port on environment variables.

I added a easy way to deploy on heroku.
Can you try?

The process are described on Readme:
[https://github.com/tiagorlampert/CHAOS#3-deploy-on-heroku](https://github.com/tiagorlampert/CHAOS#3-deploy-on-heroku)
