### ISSUE TITLE
how to build and run on windows

### ISSUE THREAD

**Issue by peterpavles** [tiagorlampert/CHAOS#72]
hello dear,

thanks for the great tool. how can we build and run this in windows using vscode?

**Comment by tiagorlampert** [comment]
Hello @peterpavles,
To run on vscode you can use the [Local Development](https://github.com/tiagorlampert/CHAOS#2-local-development) session on Readme.

But if you want to debug from vscode i'll suggest you to search on how to debug golang on vscode.
