### ISSUE TITLE
Unable to generate exe

### ISSUE THREAD

**Issue by cxaqhq** [tiagorlampert/CHAOS#84]
![image](https://user-images.githubusercontent.com/32918546/153883442-fd4a5e4d-b8a3-49de-93c1-859965c9e0de.png)
![image](https://user-images.githubusercontent.com/32918546/153883481-64b6f32e-a399-4b6e-9a86-2182f9690331.png)

**Comment by BurntDog** [comment]
Double check Windows Defender is off as it will auto turn on after some time.

**Comment by tiagorlampert** [comment]
Hello @cxaqhq,

Could you give me some details about your environment?

Are you running from a docker instance or a local development?

If you are running from code, what is your operating system? The only supported OS to run the server is Linux currently.

I added now a logger wich probably will give some details about the error on the terminal. So if you running from a local development just update your branch and get the last changes.

**Comment by cxaqhq** [comment]
root@VM-4-7-debian:~# uname -a
Linux VM-4-7-debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

**Comment by cxaqhq** [comment]
Docker is not used.

**Comment by tiagorlampert** [comment]
Could you try this test.

Run on your terminal inside the root project:

```bash
cd client

GO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o main.exe main.go

file main.exe
```

It should build a executable from the source code client, if occurs some error, probably we will see the reason.

The output should be something like this:

![image](https://user-images.githubusercontent.com/29933243/153985565-a78e682f-2e79-4bb9-ab1e-fd2f3955eb1d.png)

**Comment by cxaqhq** [comment]
![image](https://user-images.githubusercontent.com/32918546/153986288-51662b92-3c15-4f85-8014-c912f198c49d.png)

**Comment by tiagorlampert** [comment]
Probably your golang version is old than Go 1.16.
Its a requirement to be >= 1.16, i didn't specify on readme.

To see your version run:
```bash
go version
```

You should update your golang version or run from a docker instance.

**Comment by cxaqhq** [comment]
okok,Thank you for your guidance

**Comment by cxaqhq** [comment]
It can now be generated, but it was killed by WindowsDefender. Can I modify the client source bypassAV?

**Comment by tiagorlampert** [comment]
Unfortunately we don't have currently a bypass built in functionality, on the future versions probably we are work on it.

So you should use a third party project to do that.

**Comment by cxaqhq** [comment]
![image](https://user-images.githubusercontent.com/32918546/153988195-ff5255cd-2fee-4986-91a0-3bb197f5930b.png)
304? run exe not Connected Devices

**Comment by tiagorlampert** [comment]
http 304 is just the browser cache downloading the Web UI js.

The machine running the client have access to your server? check if IP and port are correct.

**Comment by cxaqhq** [comment]
![image](https://user-images.githubusercontent.com/32918546/153988855-95ad7489-2859-4f2a-97e3-301a920094a6.png)
IP prot is correct

**Comment by tiagorlampert** [comment]
I added some logs on client when connecting with server, probably now you can see some error.
You need to get the latest code from repository.

Could you try it?
Sorry for delay.
