### ISSUE TITLE
Btw dude can u post new defoult crds that used in CHAOS docker continer.

### ISSUE THREAD

**Issue by TAI-REx** [tiagorlampert/CHAOS#89]
Hello. Thank u for that good tool.
U updated default crds. 

That once not worked anymore.
default username: admin and password: admin

Can you provide new one plz?

**Comment by tiagorlampert** [comment]
Hi, sorry for delay.
The lasts docker images have an old password.

Current user and password is ```admin```.

I updated now the docker image, you can use the tag ```latest``` or ```v5.0.4``` to get the latest version (updated on readme).

```tiagorlampert/chaos:latest```

https://github.com/tiagorlampert/CHAOS#2-docker

Thanks for your feedback.
