### ISSUE TITLE
Compiling panic error

### ISSUE THREAD

**Issue by redlot10** [tiagorlampert/CHAOS#9]
OS Type: Kali Linux

GENERATE PAYLOAD
 --------------------------

 [*] Enter LHOST: 10.42.36.100
 [*] Enter LPORT: 8080
 [*] Enter name for file (.exe): exp

 [*] Compiling...
panic: open exp.exe: no such file or directory

goroutine 1 [running]:
main.GenerateCode()
    /home/tiagorlampert/CHAOS/CHAOS.go:403 +0x3c2e
main.ShowMenu()
    /home/tiagorlampert/CHAOS/CHAOS.go:165 +0x975
main.main()
    /home/tiagorlampert/CHAOS/CHAOS.go:41 +0x2a

<img width="455" alt="screen_shot" src="https://user-images.githubusercontent.com/22099611/28396112-332c0a88-6cc7-11e7-92d1-769be45a14d6.png">

**Comment by tiagorlampert** [comment]
Hi, the version compiled have a problem. Are necessary _golang_ package installed anyway. Thanks for open the issue.
You have to install Golang and run the code. I will remove the compiled version.

Run:
`# apt install golang upx-ucl -y`
`git clone https://github.com/tiagorlampert/CHAOS.git`
`cd CHAOS`
`go run CHAOS.go`
