### ISSUE TITLE
The default password admin is wrong

### ISSUE THREAD

**Issue by AuFeng111** [tiagorlampert/CHAOS#90]

**Comment by AuFeng111** [comment]
Fix the problem, :
don't build with docker environment

**Comment by tiagorlampert** [comment]
Hi, sorry for delay.
The lasts docker images have an old password.

I updated now the docker image, you can use the tag ```latest``` or ```v5.0.4``` to get the latest version (updated on readme).

```tiagorlampert/chaos:latest```

https://github.com/tiagorlampert/CHAOS#2-docker
