### ISSUE TITLE
[question]  Heroku data

### ISSUE THREAD

**Issue by Ran-Xing** [tiagorlampert/CHAOS#94]
How does heroku persist data?

**Comment by Ran-Xing** [comment]
Heroku Postgres?
Maybe read parameters from environment variables, if not empty, connect to postgress

**Comment by Ran-Xing** [comment]
https://github.com/yudai/gotty
LGTM

**Comment by tiagorlampert** [comment]
Hello @Ran-Xing,

CHAOS at the moment persist the data on a local sqlite database.
So the local instance on heroku keep the data. I understand that it is a problem if the instance dies and the database is lost.

I will consider it an improvement to optionally connect to a postgres database if some environment variable is provided. That way the data will be saved.

Thanks for your feedback, as soon as I implement it I'll let you know.

**Comment by Ran-Xing** [comment]
@tiagorlampert Do you have exclusive chat software, such as slack, telegram,
I want to get involved in your project, but it may take me a while to understand your code

**Comment by Ran-Xing** [comment]
@tiagorlampert

**Comment by tiagorlampert** [comment]
Hi @Ran-Xing,

The latest version support postgres database. You only need to specify some environment variables.

On the readme has the required environment variables to use:
https://github.com/tiagorlampert/CHAOS#3-deploy-on-heroku

**Comment by tiagorlampert** [comment]
> @tiagorlampert Do you have exclusive chat software, such as slack, telegram, I want to get involved in your project, but it may take me a while to understand your code

Yes, I have.
Could you contact me on my public email: tiagorlampert@gmail.com
